# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [2]:
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', sep='|')
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [3]:
users.groupby('occupation').age.mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [11]:
users.groupby('occupation').gender.value_counts(normalize=True).sort_values(ascending=False)

occupation     gender
doctor         M         1.000000
engineer       M         0.970149
technician     M         0.962963
retired        M         0.928571
programmer     M         0.909091
executive      M         0.906250
scientist      M         0.903226
entertainment  M         0.888889
homemaker      F         0.857143
lawyer         M         0.833333
salesman       M         0.750000
educator       M         0.726316
student        M         0.693878
healthcare     F         0.687500
other          M         0.657143
marketing      M         0.615385
writer         M         0.577778
librarian      F         0.568627
none           M         0.555556
administrator  M         0.544304
artist         M         0.535714
               F         0.464286
administrator  F         0.455696
none           F         0.444444
librarian      M         0.431373
writer         F         0.422222
marketing      F         0.384615
other          F         0.342857
healthcare     M         0.312500
student        F         0.306122
educator       F         0.273684
salesman       F         0.250000
lawyer         F         0.166667
homemaker      M         0.142857
entertainment  F         0.111111
scientist      F         0.096774
executive      F         0.093750
programmer     F         0.090909
retired        F         0.071429
technician     F         0.037037
engineer       F         0.029851
Name: proportion, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

### Step 7. For each combination of occupation and gender, calculate the mean age

### Step 8.  For each occupation present the percentage of women and men