# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [3]:
series_1 = pd.Series(np.random.randint(1,5,100))
series_2 = pd.Series(np.random.randint(1,4,100))
series_3 = pd.Series(np.random.randint(10000,30001,100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [4]:
df = pd.concat([series_1,series_2,series_3],axis=1)
df.head()

   0  1      2
0  2  1  29972
1  2  2  10992
2  1  2  19380
3  1  3  19241
4  1  1  17192

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [7]:
df.columns = ['bedrs','bathrs','price_sqr_meter']
df.head()

   bedrs  bathrs  price_sqr_meter
0      2       1            29972
1      2       2            10992
2      1       2            19380
3      1       3            19241
4      1       1            17192

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [16]:
bigcolumn = pd.concat([series_1,series_2,series_3],axis=0)
bigcolumn.head()

0    2
1    2
2    1
3    1
4    1
dtype: int64

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [17]:
bigcolumn.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=300)

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [18]:
bigcolumn.reset_index(drop=True,inplace=True)
bigcolumn.index

RangeIndex(start=0, stop=300, step=1)